### PR TITLE
docs: describe configuration parameters

### PR DESCRIPTION
**Pull request by davisjam**
Towards #2

### CODE REVIEW

**Comment by davisjam** [comment]
@tfjmp 

1. Let me know your thoughts on the approach I took. I can sketch for `camflow.ini` as well if you like this style, but you would need to check for correctness.
2. Can you check that I found the right link for the SPADE JSON format?

**Comment by tfjmp** [comment]
Yes something like that would be perfect thank you very much. I can merge this either no, or after you did the rest (if you plan to do so, otherwise I will do it in the next few days).

**Comment by davisjam** [comment]
I plan to do so.

**Comment by davisjam** [comment]
@tfjmp This PR is now as good as I can get it without reading a bunch of code.

Your additions would be appreciated. Search for "???" and "TODO" to find things I don't know about.

And of course please double-check that my interpretation was correct on everything else.

**Pull request merged**
